### ISSUE TITLE
README should describe how the DPU needs to receive its input

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/UVPlugin-rdfToVirtuosoAndCkan#1]
This is an analogous issue to https://github.com/UnifiedViews/Plugins/issues/218.

README of this DPU should document how the DPU needs to receive its input. There's no explicit input and output. Input needs to be specified as a path on file system on the server where Virtuoso is running. The documentation may include that in this setup the DPU is typically run with the `run_after` edge connected to a DPU that loads data to the filesystem.

**Comment by ghost** [comment]
rdfto virtuoso and ckan has rdf Input, but nevermind, this DPU is still under construction (contact me for details)

**Comment by jindrichmynarz** [comment]
Sorry, my mistake. Closing the issue as invalid.
