### ISSUE TITLE
actual documentation is missing

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/UVPlugin-rdfToVirtuosoAndCkan#5]
These shall be add to [backend.properties](https://github.com/UnifiedViews/Packages/blob/master/unifiedviews-backend-mysql/src/deb/etc/unifiedviews/backend-config.properties) after upload dpu. Please, update doc and explain all properties.

```
dpu.uv-l-rdfToVirtuosoAndCkan.dataset.uri.pattern = https://host/internalcatalog/dataset/{0}
dpu.l-rdfToVirtuoso.username = dba
dpu.l-rdfToVirtuoso.password = dba
dpu.l-rdfToVirtuoso.jdbc.url = jdbc:virtuoso://localhost:1111/charset=UTF-8/
```

**Comment by ghost** [comment]
updated here https://github.com/OpenDataNode/UVPlugin-rdfToVirtuosoAndCkan/commit/34577d36bebf96701ee52e9751c1b494b6f5b246
current doc: https://github.com/OpenDataNode/UVPlugin-rdfToVirtuosoAndCkan/blob/develop/README.md 

resolved
